apiVersion: v1
kind: PersistentVolume
metadata:
  name: ubuntu-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"  # 노드의 실제 디렉토리 경로, 이 경로는 모든 노드에서 동일해야 합니다.
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ubuntu-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-develop-env
  labels:
    app: ubuntu-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-dev
  template:
    metadata:
      labels:
        app: ubuntu-dev
    spec:
      containers:
      - name: ubuntu-dev
        image: ubuntu:22.04
        ports:
        - containerPort: 22
        securityContext:
          capabilities:
            add: ["NET_ADMIN", "SYS_TIME"]
        command:
        - /bin/bash
        - -c
        - |
          apt-get update && apt-get install -y openssh-server && \
          mkdir /var/run/sshd && \
          echo 'root:root' | chpasswd && \
          echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config && \
          echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config && \
          /usr/sbin/sshd -D
        volumeMounts:
        - mountPath: /data
          name: ubuntu-storage
      volumes:
      - name: ubuntu-storage
        persistentVolumeClaim:
          claimName: ubuntu-pvc          
        # resources:
        #   limits:
        #     memory: "512Mi"
        #     cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: ubuntu-service
spec:
  selector:
    app: ubuntu-dev
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
      nodePort: 30022
  type: NodePort


